---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2017, Jean-Philippe Evrard <jean-philippe.evrard@rackspace.co.uk>

- name: Test lookups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    # Version is set to enforce a specific list for testing, and
    # avoid the need to update the test in the future.
    - name: Cloning data for the lookup
      git:
        repo: https://github.com/openstack/openstack-ansible-os_glance.git
        dest: /tmp/checkout-role
        version: 66e8dc3b6eb3032888e5da9fbf869c278e75b5e6
    - name: Create an empty list of packages to install
      set_fact:
        packages_to_install_list: []
        xenial_full_list:
          - rpcbind
          - rsync
          - git
          - nfs-common
    - name: Iterate to construct a list of all the packages_to_install
      set_fact:
        packages_to_install_list: "{{ packages_to_install_list }} + [ '{{ item }}' ]"
      with_packages_to_install:
        - from:
            - /tmp/checkout-role
          for: xenial
    - debug:
        var: packages_to_install_list
    - name: Compare the two full lists
      assert:
        that:
          - packages_to_install_list | difference(xenial_full_list) == []
          - packages_to_install_list | length == 4
    - name: Filter using pkg black list using regexps
      set_fact:
        install_package: "{{ item }}"
      with_packages_to_install:
        - from:
            - /tmp/checkout-role
          for: xenial
          pkg_blacklist:
            - nfs.*
            - rsync
            - (rpcbind|rpcfoo)
    - name: Verify that test black list only contains git
      assert:
        that:
          - install_package == "git"

