---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Push the changes
  hosts: mirrors
  vars_files:
    - container-vars.yml
  vars:
    repo_remote_path: "/var/www/repo"
  tasks:
    - name: Ensure metatadata folder exists
      file:
        path: "{{ repo_remote_path }}/meta/1.0/"
        state: directory
        owner: "{{ webserver_owner }}"
        group: "{{ webserver_group }}"

    - name: Publish metadata
      copy:
        src: "/opt/list"
        dest: "{{ repo_remote_path }}/meta/1.0/index-system"
        owner: "{{ webserver_owner }}"
        group: "{{ webserver_group }}"

    - name: Ensure destination folders exist
      file:
        path: "{{ repo_remote_path }}{{ item.split(';')[5] }}"
        state: directory
        owner: "{{ webserver_owner }}"
        group: "{{ webserver_group }}"
      # With the below sample line in the metadata file, we need to ensure
      # that we only get lines that are for this release. We do this by
      # grepping for the 4th element in the ';'-delimited list.
      # ubuntu;trusty;amd64;cinder-r14.1.0rc1;20170511;/lxc-images/ubuntu/trusty/amd64/cinder-r14.1.0rc1/20170511
      with_lines: "grep '-{{ rpc_release }};' /opt/list"

    # To ensure that the push/delete removes any previous builds
    # for the same variant, we choose to push the built artifact's
    # parent folder to rpc-repo.
    # eg:
    # artifact directory: lxc-images/ubuntu/trusty/amd64/cinder-r14.1.0rc1/20170509/
    # rsync src: lxc-images/ubuntu/trusty/amd64/cinder-r14.1.0rc1
    # rsync dest: lxc-images/ubuntu/trusty/amd64/
    - name: Publish container artifacts
      synchronize:
        src: "{{ lxc_image_folder }}{{ item.split(';')[5] | dirname }}"
        dest: "{{ repo_remote_path }}{{ (item.split(';')[5] | dirname) | dirname }}/"
        mode: push
        delete: yes
        recursive: yes
        rsync_opts:
          - "--chown=nginx:www-data"
      with_lines: "grep '-{{ rpc_release }};' /opt/list"
      register: synchronize
      until: synchronize | success
      retries: 5
      delay: 5

